### ISSUE TITLE
Ballast for tracks that are not parallel have transparent gaps.

### ISSUE THREAD

**Issue by tabytac** [Yozora3/JpPlusTracks#10]
### I noticed that the bottom side of a ballast (not urban tiles though) is missing if the tile next to it is not parallel to it like below:

![image](https://github.com/user-attachments/assets/00d10af9-a1ce-4aa0-80b8-f0d5382887a3)
![image](https://github.com/user-attachments/assets/fc5fda25-5b0f-4e49-8ad2-9ddc5fd9091c)

### Here's a realistic situation where the missing pixels show, not just the test tracks I placed for this issue:

![image](https://github.com/user-attachments/assets/1309a35d-add0-47ac-a9dc-c636afdeac00)

**Comment by Yozora3** [comment]
It was sort of intentional, as I wanted to imitate ballast feel, that it's not linear.
I'll fix this with making the SE and SW sides full tile

**Comment by Yozora3** [comment]
fixed in [da68ee0](https://github.com/Yozora3/JpPlusTracks/commit/da68ee009af021fb89eae17dce97499daf6dfb68)
